Add catcol as colour name to use the category colour for the icon
discourse/discourse-category-icons pull request #8
Opened 2020-09-25 20:52 UTC by rogercreagh

Allow catcol as colour specifier to select the category badge colour.

eg "test,hands-helping,catcol,partial"

Most useful with the partial name match so that, in the example, the same icon can be used for all categories with "test" in their slug but they will each pick up their own category colour rather than all using the same. Also provides a quick alternative to having to select a colour for a one-off icon (exact match) - simply use the category colour.

This will also be useful with a proposed further new option to have the icon replace the category stripe whilst maintaining the category colour hint - to be subject of a future PR

2020-09-25 22:50 UTC, pmusaraj requested changes
This looks like a useful change, thanks! I would prefer to call the special option "categoryColor", it's easier to understand than "catcol".

Can you also remove the extra files in the commit? Looks like they are coming from Eclipse.

2020-09-26 15:02 UTC, rogercreagh commented
Whoops - sorry I though Eclipse should have filtered them out. They should be gone now and also I changed catcol to categoryColour as you suggested.
I haven't changed the version number in the about.json (it doesn't seem to be there) and also when I tried the current (prior to this PR) on a Discourse 2.5 install it didn't seem to work, although fine on 2.6. Should there be a minimum discourse version specified in there?

2020-09-28 08:00 UTC, ZogStriP commented on javascripts/discourse/initializers/category-icons.js
> +        let itemColor = iconItem[2] == 'categoryColour' ? `style="color: #${color}"` : iconItem[2] ? `style="color: ${iconItem[2]}"` : "";
Looks like the indentation is off here.

2020-09-28 08:00 UTC, ZogStriP commented on javascripts/discourse/initializers/category-icons.js
> +        ///  let itemColor = iconItem[2] ? `style="color: ${iconItem[2]}"` : "";
Can you remove that comment?

2020-09-28 12:56 UTC, rogercreagh commented on javascripts/discourse/initializers/category-icons.js
> +        let itemColor = iconItem[2] == 'categoryColour' ? `style="color: #${color}"` : iconItem[2] ? `style="color: ${iconItem[2]}"` : "";
done

2020-09-28 12:56 UTC, rogercreagh commented on javascripts/discourse/initializers/category-icons.js
> +        ///  let itemColor = iconItem[2] ? `style="color: ${iconItem[2]}"` : "";
Done

2020-09-28 13:04 UTC, pmusaraj commented on .gitignore
> +.discourse-site
Sorry to keep pushing back on this @rogercreagh, but this `.gitignore` file showed up again...

2020-09-28 13:36 UTC, merged